import {writeFileSync,readFileSync,copyFileSync,existsSync,mkdirSync,statSync} from 'node:fs';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {DIM,MEASURES,SOURCES,SOURCE_DIVERGENCES,getPlan,REVISION} from '../dist/specification.js';
import {DEFAULT_CONFIG} from '../dist/configuration.js';
import {DATA} from '../dist/data.js';
const dest='dist/assets/evidence',tmp='/private/tmp/gv72-v2-audit';mkdirSync(dest,{recursive:true});
const read=p=>JSON.parse(readFileSync(p,'utf8'));
const clean=v=>{if(typeof v==='string'){if(v.startsWith('/Users/')||v.startsWith('/private/'))return path.basename(v);return v.replaceAll('/Users/claraazevedo/Documents/global-lead-scraper/green-village-72/','');}if(Array.isArray(v))return v.map(clean);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clean(x)]));return v;};
const save=(name,value)=>writeFileSync(path.join(dest,name),JSON.stringify(clean(value),null,2)+'\n');
const dimensions={revision:REVISION,units:'metres',axes:{x:'right',y:'up',z:'main entrance'},origin:'Centre of floor surface',sourcePrecision:'Exterior integer mm as printed. Interior trace proportions and unmeasured details remain estimates; floating-point precision does not improve source certainty.',numericToleranceM:1e-7,manufacturingTolerance:null,parameters:DIM,measures:MEASURES,sources:SOURCES,divergences:SOURCE_DIVERGENCES,layouts:DATA.layouts.map(x=>getPlan({...DEFAULT_CONFIG,layout:x.id})),areasNote:'Exterior bounding rectangle: 73.396 m²; commercial name: 72 m². Exact stepped footprint/useful certified area not provided. Interior areas computed with assumed wall sections; additional canopy and porch excluded.'};save('dimensions.json',dimensions);
for(const [from,to]of [['geometry-v2/geometry-v2-final-report.json','geometry-validation.json'],['geometry-v2/source-regression-fixtures.json','source-regression-fixtures.json'],['geometry-v2/electrical-evidence.json','electrical-validation.json'],['geometry-v2/plumbing-evidence.json','plumbing-validation.json'],['final-browser/final-browser-report.json','browser-final.json'],['films/validation.json','films-validation.json'],['films/video-colour-validation.json','films-colour-validation.json'],['films/asset-manifest.json','films-manifest.json'],['final-browser/quick.json','browser-snapshot.json'],['final-browser/flows.json','browser-flows.json'],['final-browser/robust-mobile.json','browser-robustness.json'],['final-browser/pdf-inspection.json','pdf-validation.json'],['final-browser/fixes-perf.json','browser-performance.json']]){if(existsSync(path.join(tmp,from)))save(to,read(path.join(tmp,from)));}
for(const mode of ['exterior','interior','structure'])for(const size of ['desktop','mobile']){const before=path.join(tmp,'baseline',`${size}-${mode}.png`),after=path.join(tmp,'final-browser',`${size}-${mode}-comparison.png`);for(const [src,n]of [[before,`before-${size}-${mode}.png`],[after,`after-${size}-${mode}.png`]])if(existsSync(src))copyFileSync(src,path.join(dest,n));}
for(const file of ['material-comparison.png','pdf-page-1.png','pdf-page-2.png'])if(existsSync(path.join(tmp,'final-browser',file)))copyFileSync(path.join(tmp,'final-browser',file),path.join(dest,file));
const assets=['presentation-v2.mp4','expansion-v2.mp4','presentation-v2-poster.jpg','expansion-v2-poster.jpg'].map(file=>({file:'../'+file,bytes:statSync('dist/assets/'+file).size,sha256:createHash('sha256').update(readFileSync('dist/assets/'+file)).digest('hex')}));save('delivered-media.json',{revision:REVISION,assets});
const sourceFiles=['specification.js','configuration.js','model.js','material-library.js','material-data.js','stage.js','app.js','plan-svg.js','style.css','index.html'];save('source-hashes.json',{revision:REVISION,files:sourceFiles.map(file=>({file,sha256:createHash('sha256').update(readFileSync('dist/'+file)).digest('hex')}))});
console.log('Evidence assets assembled.');
