// Independent R9 audit. Run with --dist <dist directory> --out <report.json>.
// Uses only the actual makeHouse/updateExpansion implementation; no prototype transform.
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import crypto from 'node:crypto';
const arg=(name,fallback)=>{const i=process.argv.indexOf(name);return i<0?fallback:process.argv[i+1];};
const DIST=path.resolve(arg('--dist',path.join(path.dirname(fileURLToPath(import.meta.url)),'../dist'))),OUTPUT=arg('--out',null),frames=Number(arg('--frames','1001'));
if(!Number.isInteger(frames)||frames<101)throw new Error('Use at least101 frames.');
const moduleAt=f=>import(pathToFileURL(path.join(DIST,f)).href);
const T=await moduleAt('vendor/three.module.js'),{makeHouse}=await moduleAt('model.js'),{DATA}=await moduleAt('data.js');
const results=[],layouts=DATA.layouts.map(x=>x.id),roofClearance=.008;
const sourceFiles=['model.js','specification.js','configuration.js','data.js','interior-detail.js','interior-references.js','model-layers.js','vendor/three.module.js','vendor/three.core.js'];
const hashes=()=>Object.fromEntries(sourceFiles.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(DIST,f))).digest('hex')]));const startHashes=hashes();
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),axes=[V(1,0,0),V(0,1,0),V(0,0,1)],identity=new T.Matrix4();
function obb(box,m){const c=box.getCenter(V()).applyMatrix4(m),h=box.getSize(V()).multiplyScalar(.5),q=new T.Quaternion(),s=V();m.decompose(V(),q,s);return {c,h:h.multiply(s),axes:axes.map(a=>a.clone().applyQuaternion(q))};}
function sat(a,b){const d=b.c.clone().sub(a.c);let least=Infinity;for(const n of [...a.axes,...b.axes,...a.axes.flatMap(x=>b.axes.map(y=>x.clone().cross(y)))]){if(n.lengthSq()<1e-12)continue;n.normalize();const radius=o=>o.axes.reduce((r,x,i)=>r+Math.abs(n.dot(x))*o.h.getComponent(i),0),overlap=radius(a)+radius(b)-Math.abs(d.dot(n));if(overlap<=1e-6)return 0;least=Math.min(least,overlap);}return least;}
function components(mesh){const g=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry,p=g.attributes.position,N=p.count,parents=Array.from({length:N},(_,i)=>i),find=i=>{while(parents[i]!==i){parents[i]=parents[parents[i]];i=parents[i];}return i;},join=(a,b)=>{a=find(a);b=find(b);if(a!==b)parents[b]=a;},seen=new Map();for(let i=0;i<N;i++){const key=[p.getX(i),p.getY(i),p.getZ(i)].map(x=>Math.round(x*1e7)).join(',');if(seen.has(key))join(i,seen.get(key));else seen.set(key,i);if(i%3)join(i,i-i%3);}const found=new Map();for(let i=0;i<N;i++){const id=find(i);if(!found.has(id))found.set(id,new T.Box3());found.get(id).expandByPoint(V(p.getX(i),p.getY(i),p.getZ(i)));}if(g!==mesh.geometry)g.dispose();return [...found.values()].map((box,i)=>({box,mesh,id:mesh.name+'#'+i}));}

for(const layout of layouts){const h=makeHouse({layout,view:'expansion',expansion:1});h.updateExpansion(1);h.root.updateMatrixWorld(true);const bodies=[];
const add=(id,roots,moving=false)=>{const pieces=[];for(const root of roots)root.traverse(o=>{if(o.isMesh)pieces.push(...components(o));});bodies.push({id,roots,pieces,moving});};
for(const a of h.floorAssemblies)add('floor '+a.dir,a.pivots);
for(const a of h.roofAssemblies)add('roof '+a.dir,a.pivots,roofClearance>0);
for(const a of h.sideAssemblies){add('side-panel '+a.dir,[a.pivot],true);add('side-posts '+a.dir,[a.framePivot]);}
for(const a of h.endAssemblies)add('end '+a.dir+'/'+a.front,[a.pivot]);
const covered=new Set(bodies.flatMap(b=>b.roots));for(const name of ['structure','floor','floorLayers','roof','shell','supports']){const pieces=[];h.groups[name].traverse(o=>{if(!o.isMesh)return;for(let p=o;p;p=p.parent)if(covered.has(p))return;pieces.push(...components(o));});if(pieces.length)bodies.push({id:'fixed '+name,roots:[],pieces,moving:false});}
const assertions=[],record=(name,pass,detail=null)=>{if(!pass)assertions.push({name,detail});};const worldBase=new Map();h.root.traverse(o=>{if(o.isMesh)worldBase.set(o,o.matrixWorld.clone());});const attachments=[];for(const a of h.sideAssemblies)a.pivot.traverse(o=>{if(o.isMesh)attachments.push({dir:a.dir,mesh:o,root:a.pivot,local:new T.Matrix4().copy(a.pivot.matrixWorld).invert().multiply(o.matrixWorld)});});
function build(){for(const b of bodies){b.aabb=new T.Box3();for(const c of b.pieces){c.obb=obb(c.box,c.mesh.matrixWorld);c.aabb=c.box.clone().applyMatrix4(c.mesh.matrixWorld);b.aabb.union(c.aabb);}}}
function candidates(){const hits=[];for(let a=0;a<bodies.length;a++)for(let b=a+1;b<bodies.length;b++){const A=bodies[a],B=bodies[b];if(!A.moving&&!B.moving||!A.aabb.intersectsBox(B.aabb))continue;for(let i=0;i<A.pieces.length;i++)for(let j=0;j<B.pieces.length;j++){const x=A.pieces[i],y=B.pieces[j];if(!x.aabb.intersectsBox(y.aabb))continue;const overlap=sat(x.obb,y.obb);if(overlap>.00005)hits.push({key:a+'/'+b+'/'+i+'/'+j,a:A.id,b:B.id,pieceA:x.id,pieceB:y.id,overlap});}}return hits;}
build();const baseline=new Map(candidates().map(x=>[x.key,x.overlap])),regressions=new Map(),samples=[],prevCorners=new Map();let minY=Infinity,maxAttachmentError=0,maxOutwardBacktrack=0,axisHalfspaceViolations=0,maxFixedMatrixError=0,maxFormulaError=0,nonFiniteCoordinateCount=0;const movingMeshes=new Set(bodies.filter(b=>b.moving).flatMap(b=>b.pieces.map(p=>p.mesh)));const smooth=(a,b,p)=>{const t=Math.max(0,Math.min(1,(p-a)/(b-a)));return t*t*(3-2*t);};
for(const a of h.sideAssemblies)for(const b of bodies.filter(x=>x.id==='side-panel '+a.dir))for(const c of b.pieces)for(const x of [c.box.min.x,c.box.max.x])for(const y of [c.box.min.y,c.box.max.y])for(const z of [c.box.min.z,c.box.max.z]){const v=V(x,y,z).applyMatrix4(c.mesh.matrixWorld);if(a.dir*v.x<2.99-1e-8||v.y<0)axisHalfspaceViolations++;}
for(let n=0;n<frames;n++){const p=n/(frames-1),pose=h.updateExpansion(p);h.root.updateMatrixWorld(true);build();const alpha=Math.PI/2*(1-smooth(0,.9,p)),lift=.008*(1-smooth(.9,1,p));record('state-scope',pose.scope==='longitudinal-wall-raising'&&pose.referenceOnly===false);record('state-no-legacy-fields',!['roof','floor','ends','roofDock','postsDock'].some(k=>Object.hasOwn(pose,k)));record('source-stage-metadata',pose.sourcePhase==='2–3'&&pose.axisStatus==='estimated');record('state-angle',Math.abs(pose.angle-alpha)<1e-12);record('state-roof-clearance',Math.abs(pose.roofLift-lift)<1e-12);record('end-wings-omitted',h.endAssemblies.every(a=>a.g.visible===false));record('core-ends-visible',h.groups.shell.visible===true);for(const [m,base]of worldBase)if(!movingMeshes.has(m))for(let i=0;i<16;i++)maxFixedMatrixError=Math.max(maxFixedMatrixError,Math.abs(base.elements[i]-m.matrixWorld.elements[i]));for(const b of bodies.filter(b=>b.id.startsWith('side-panel'))){minY=Math.min(minY,b.aabb.min.y);const dir=b.id.endsWith('-1')?-1:1;for(const [i,c]of b.pieces.entries())for(let k=0;k<8;k++){const pt=V(k&1?c.box.min.x:c.box.max.x,k&2?c.box.min.y:c.box.max.y,k&4?c.box.min.z:c.box.max.z).applyMatrix4(c.mesh.matrixWorld),key=b.id+'/'+i+'/'+k,current=dir*pt.x;const basePt=V(k&1?c.box.min.x:c.box.max.x,k&2?c.box.min.y:c.box.max.y,k&4?c.box.min.z:c.box.max.z).applyMatrix4(worldBase.get(c.mesh)),angle=dir*alpha,dx=basePt.x-dir*2.99,expected=V(dir*2.99+dx*Math.cos(angle)-basePt.y*Math.sin(angle),dx*Math.sin(angle)+basePt.y*Math.cos(angle),basePt.z);maxFormulaError=Math.max(maxFormulaError,expected.distanceTo(pt));if(!pt.toArray().every(Number.isFinite))nonFiniteCoordinateCount++;if(prevCorners.has(key))maxOutwardBacktrack=Math.max(maxOutwardBacktrack,prevCorners.get(key)-current);prevCorners.set(key,current);}}
for(const a of attachments){const m=new T.Matrix4().copy(a.root.matrixWorld).invert().multiply(a.mesh.matrixWorld);for(let i=0;i<16;i++)maxAttachmentError=Math.max(maxAttachmentError,Math.abs(m.elements[i]-a.local.elements[i]));}
for(const hit of candidates()){const initial=baseline.get(hit.key)||0;if(hit.overlap<=initial+.00005)continue;const key=hit.a+' / '+hit.b;if(!regressions.has(key))regressions.set(key,{pair:key,firstP:p,lastP:p,maxOverlapM:0,example:null});const s=regressions.get(key);s.lastP=p;if(hit.overlap>s.maxOverlapM){s.maxOverlapM=hit.overlap;s.example={p,...hit,finalBaselineOverlapM:initial};}}
if([0,Math.round((frames-1)*.25),Math.round((frames-1)*.5),Math.round((frames-1)*.75),Math.round((frames-1)*.9),frames-1].includes(n))samples.push({p,pose,sideBounds:bodies.filter(b=>b.id.startsWith('side-panel')).map(b=>({id:b.id,bounds:b.aabb}))});}
let endpointError=0;for(const [m,base]of worldBase)for(let i=0;i<16;i++)endpointError=Math.max(endpointError,Math.abs(base.elements[i]-m.matrixWorld.elements[i]));const cycleErrors=[];let cycleCount=0;const capture=()=>[...worldBase.keys()].map(o=>({m:o.matrixWorld.clone(),visible:o.visible}));
for(const progress of [0,.25,.5,.75,.9,1]){h.setView('expansion');h.updateExpansion(progress);h.root.updateMatrixWorld(true);const before=capture();for(const view of ['exterior','interior']){h.setView(view);h.root.updateMatrixWorld(true);const finalError=Math.max(...[...worldBase].flatMap(([m,base])=>base.elements.map((v,i)=>Math.abs(v-m.matrixWorld.elements[i]))));if(finalError>1e-9)cycleErrors.push({progress,view,error:finalError,kind:'assembled-transform-after-exit'});if(!h.endAssemblies.every(a=>a.g.visible))cycleErrors.push({progress,view,kind:'end-panel-restore'});h.setView('expansion');h.updateExpansion(progress);h.root.updateMatrixWorld(true);const again=capture();let error=0,visibilityMismatches=0;for(let i=0;i<before.length;i++){for(let j=0;j<16;j++)error=Math.max(error,Math.abs(before[i].m.elements[j]-again[i].m.elements[j]));if(before[i].visible!==again[i].visible)visibilityMismatches++;}if(error>1e-9||visibilityMismatches)cycleErrors.push({progress,view,error,visibilityMismatches,kind:'reentry-pose'});cycleCount++;}}
h.setView('expansion');for(const open of [false,true,false]){h.setDoors(open);h.root.updateMatrixWorld(true);const before=h.doors.map(d=>d.pivot.matrixWorld.toArray());for(const q of [0,.25,.5,.9,1]){h.updateExpansion(q);h.root.updateMatrixWorld(true);record('passage-door-independent',h.doors.every((d,i)=>d.pivot.matrixWorld.elements.every((v,k)=>Math.abs(v-before[i][k])<1e-12)));}}h.setDoors(false);h.setView('exterior');h.root.updateMatrixWorld(true);record('final-reference-end-panels-visible',h.endAssemblies.every(a=>a.g.visible));
results.push({layout,frames,roofClearance,axisX:2.99,axisY:0,assertionFailures:assertions,maxFixedMatrixError,maxFormulaError,nonFiniteCoordinateCount,cycleCount,cycleErrors,componentCounts:bodies.map(b=>({id:b.id,count:b.pieces.length,moving:b.moving})),baselineContactCount:baseline.size,regressions:[...regressions.values()],minPanelY:minY,maxOutwardBacktrack,maxAttachmentError,endpointError,axisHalfspaceViolations,samples});h.dispose();}
const endHashes=hashes(),sourceStable=JSON.stringify(startHashes)===JSON.stringify(endHashes),report={status:sourceStable&&results.every(r=>!r.regressions.length&&!r.assertionFailures.length&&!r.cycleErrors.length&&r.minPanelY>=0&&r.maxOutwardBacktrack<1e-8&&r.maxAttachmentError<1e-8&&r.endpointError<1e-8&&r.maxFixedMatrixError<1e-8&&r.maxFormulaError<1e-8&&!r.nonFiniteCoordinateCount)?'PASS':'REVIEW_REQUIRED',testedAt:new Date().toISOString(),dist:DIST,sourceStable,startHashes,endHashes,framesPerLayout:frames,layouts:layouts.length,implementation:'Actual makeHouse.updateExpansion from the specified dist directory; no replacement transform in the harness.',method:'Connected-component OBB SAT; 0.05mm excess over explicit final structural contacts. Static end panels/posts/core/floors/roof included as obstacles. Intersections within intended final joints remain documented baseline. Furniture/interior partitions/optional canopy and porch omitted from installation demonstration. Every component-corner outward direction and mathematical pose independently checked. Reentry explicitly reapplies the requested slider value; model.setView intentionally returns to final pose when leaving expansion.',results};
if(OUTPUT){fs.mkdirSync(path.dirname(path.resolve(OUTPUT)),{recursive:true});fs.writeFileSync(OUTPUT,JSON.stringify(report,null,2)+'\n');}
console.log(JSON.stringify({status:report.status,sourceStable,layouts:report.layouts,framesPerLayout:frames,totalPoses:frames*layouts.length,cycles:results.reduce((n,r)=>n+r.cycleCount,0),newIntersections:results.reduce((n,r)=>n+r.regressions.length,0),assertionFailures:results.reduce((n,r)=>n+r.assertionFailures.length+r.cycleErrors.length,0)},null,2));if(report.status!=='PASS')process.exitCode=1;
